module.exports = {
  content: [
    './resources/**/*.antlers.html',
    './resources/**/*.blade.php',
    './resources/**/*.vue',
    './resources/**/*.svg',
    './content/**/*.md'
  ],
  theme: {
    fluidSpacing: {
      xxs: '13px',
      xs: '14px',
      sm: '15px',
      100: 'var(--size-100)',
      200: 'var(--size-200)',
      300: 'var(--size-300)',
      400: 'var(--size-400)',
      500: 'var(--size-500)',
      600: 'var(--size-600)',
      700: 'var(--size-700)',
      750: 'calc(var(--size-700) * 1.2)',
      800: 'var(--size-800)',
      850: 'calc(var(--size-800) * 1.2)',
      900: 'var(--size-900)',
      lg: 'var(--size-lg)',
      xl: 'var(--size-xl)',
      xxl: 'calc(var(--size-xl) * 1.5)',
      gutter: 'var(--gutter)',
      container: 'var(--container-padding)',
    },
    extend: {
      padding: (theme) => theme('fluidSpacing'),
      margin: (theme) => theme('fluidSpacing'),
      spacing: (theme) => theme('fluidSpacing'),
      gap: (theme) => theme('fluidSpacing'),
      fontSize: (theme) => theme('fluidSpacing'),
      flexGrow: {
        9: '9999',
      },
      transitionTimingFunction: {
        'custom': 'cubic-bezier(0,.1,.05,.99)',
      },
      lineHeight: {
        flat: '1.1',
      },
      aspectRatio: {
        '1/1': '1 / 1',
        '1/2': '1 / 2',
        '2/3': '2 / 3',
        '3/4': '3 / 4',
        '4/5': '4 / 5',
        '5/6': '5 / 6',
        '3/1': '3 / 1',
        '3/2': '3 / 2',
        '5/2': '5 / 2',
        '5/3': '5 / 3',
        '16/8': '16 / 8',
      },
      colors: {
        'primary-glare': '#6FE1DC',
        'primary': '#16d9d0',
        'primary-shade': '#0CBCB4',
        'secondary': '#11A876',
        'dark-glare': '#124F7E',
        'dark': '#003A65',
        'dark-shade': '#002037',
        'black': '#121B2B',
        'white': '#ffffff',
        'light-glare': '#F5F5F6',
        'light': '#E9E9EC',
        'light-shade': '#DDDDE3',
      },
      fontFamily: {
        base: ['Dosis','Helvetica','Arial','Lucida','sans-serif'],
        secondary: ['Dosis','Helvetica','Arial','Lucida','sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
  ],
}
