sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          input_type: text
          antlers: false
          display: Name
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: phone
        field:
          input_type: tel
          antlers: false
          display: Phone
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: email
        field:
          input_type: email
          antlers: false
          display: Email
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
