title: Meta
fields:
  -
    handle: title
    field:
      input_type: text
      antlers: false
      display: Title
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: description
    field:
      antlers: false
      display: Description
      type: textarea
      icon: textarea
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
